FROM node:20-slim

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

# Generujemy Prisma Client (nie wymaga DB)
RUN npx prisma generate

COPY . .

RUN npx next build

EXPOSE 3000

CMD ["npm", "run", "start"]
